### PR TITLE
Fix spaghettiness

### LINKED ISSUE #6: [fed] parliament streams stay live after due ending
The Federal parliament keeps their streams up for hours after their marked ending time. We could scrape the ending times from the site and check them in the backend.

image

### LINKED ISSUE #9: pip package has wrong version
I'm getting this error trying to install with pip:

```sh
pip install legistream-backend 
Collecting legistream-backend
Downloading legistream-backend-1.4.17-2.tar.gz (15 kB)
Installing build dependencies ... done
Getting requirements to build wheel ... done
Preparing wheel metadata ... done
ERROR: Requested legistream-backend from https://files.pythonhosted.org/packages/38/31/f9fa5abce501849b2fec688d0d56e7001e1d949cdd2841c77aa501aa4920/legistream-backend-1.4.17-2.tar.gz#sha256=ce7019bbea504c779e68a6c7015c28d101438e4c4b29fae154728f308a0e43e2 has different version in metadata: '1.4.17'
```

### PR DESCRIPTION
**Pull request by king-millez**
# Anti spaghetti brigade

This pull request is similar to our [ausbills update](https://github.com/OpenGovAus/ausbills/pull/54) which refactors the code into a consistent model-based system.

## Key changes

The main difference is the new `StreamModel` `dataclass`, which creates a standard for stream objects that all sites must follow, e.g stream URLs, titles, and their live statuses.

This method will make it easy for [the web app](https://github.com/OpenGovAus/legistream-site) to simply utilise `importlib` to loop through the various parliaments, rather than the stupid system I wrote in late 2020 which is stupid and bad.

The parliament modules have also all been moved into the `site` directory, so in the event that a jurisdiction secedes from Australia, or New Zealand becomes an Australian state, Legistream can quickly and automatically adapt to the minor changes.

## Closes Issues
- Fixes #6
- Closes #9

### CODE REVIEW

**Comment by tomlister** [comment]
LGTM

**Comment by tomlister** [comment]
Still need hosting?

**Comment by king-millez** [comment]
> Still need hosting?

Possibly, was using DigitalOcean previously but if you have a better option I'm all ears!

**Comment by tomlister** [comment]
In that case, I suggest checking out Amazon Lightsail. Starting at $3.5/month for the lowest tier. Free 3 months trial.

You can always go serverless for free! Shout out https://vercel.com
Though, you'd need some major refactoring of your code.

**Comment by king-millez** [comment]
> In that case, I suggest checking out Amazon Lightsail. Starting at $3.5/month for the lowest tier. Free 3 months trial.
> 
> You can always go serverless for free! Shout out https://vercel.com
> Though, you'd need some major refactoring of your code.

**Comment by king-millez** [comment]
Tried to close comment box and closed PR, classy.

**Comment by king-millez** [comment]
# Parliament schedules for testing:

## ACT

31-8-21

## QLD

13-8-21

31-8-21

## Vic

17-8-21

## Tas

24-8-21

## SA

13-8-21

24-8-21

## WA

17-8-21

## NSW

16-8-21

**Pull request merged**
